just compiling with torch==2.0.1 on ubuntu18.04

diff --git a/docker/Dockerfile_build b/docker/Dockerfile_build
--- a/docker/Dockerfile_build
+++ b/docker/Dockerfile_build
@@ -33,9 +33,21 @@ ENV ACloudViewer_DEV=/root \
     ACloudViewer_BUILD=/root/ACloudViewer/build \
     ACloudViewer_INSTALL=/root/install
 
-ENV PATH="/root/miniconda3/bin:$PATH"
+ENV PATH="/root/miniconda3/bin:$PATH" \
+    CONDA_EXE="/root/miniconda3/bin/conda"
 ENV CLOUDVIEWER_ML_ROOT=/root/CloudViewer-ML
 RUN git clone --depth 1 https://github.com/Asher-1/CloudViewer-ML.git ${CLOUDVIEWER_ML_ROOT}
+
+RUN if [ -n "$CONDA_EXE" ]; then \
+        CONDA_ROOT=$(dirname $(dirname "$CONDA_EXE")); \
+    elif [ -n "$CONDA_PREFIX" ]; then \
+        CONDA_ROOT=$(dirname "$CONDA_PREFIX"); \
+    else \
+        echo "Failed to find Miniconda3 install path..."; \
+        exit 1; \
+    fi && \
+    echo "CONDA_ROOT is set to: $CONDA_ROOT" && \
+    source "$CONDA_ROOT/etc/profile.d/conda.sh" 
 
 COPY . ${ACloudViewer_DEV}/ACloudViewer
 WORKDIR ${ACloudViewer_DEV}/ACloudViewer
